package com.mh.rfid.enums;

public enum EstadoMensajeType {
	PENDIENTE_ENVIAR,
	CORREGIDO,
	
	REINTENTAR_ENVIO,
	ERROR_DURANTE_ENVIO, 
	
	PENDIENTE_VERIFICAR, 
	REINTENTAR_VERIFICACION,
	ERROR_DURANTE_VERIFICACION,
	
	INCONSISTENTE,
	INTEGRADO
}
